### ISSUE TITLE
is this what it's supposed to look like?

### ISSUE THREAD

**Issue by matthewmueller** [duojs/duojs.org#3]
@ianstormtaylor tried running `make server`

And got it to install and start the server, but when I go to `localhost:8888`, I get:

![duojs](https://i.cloudup.com/VGnLhdsz6n.png)

Is this right? haha

**Comment by ianstormtaylor** [comment]
Hahaha yup, didn't do anything in terms of concept, just setup the infrastructure for it all. But might start into that now. I can use those colors from the logo, and I can probably just recreate the shapres of the logo in Sketch myself and export it so that we have a common SVG to reference elsewhere.

Could you make a `duojs/logo` repo that I can push to as well?

Do you have a specific image you want behind the logo for parallaxing? I think there was another space-ier one from before?

**Comment by matthewmueller** [comment]
> Hahaha yup, didn't do anything in terms of concept, just setup the infrastructure for it all. But might start into that now. I can use those colors from the logo, and I can probably just recreate the shapres of the logo in Sketch myself and export it so that we have a common SVG to reference elsewhere.

Hahaha gotcha. sexy site :-P

> Could you make a duojs/logo repo that I can push to as well?

yep, need to figure out this teams thing. do you know if there's any option that lets people create new repos but have push access to certain ones? I figure that's the best route if it's possible: let anyone create anything, and then they own that repo, but can't push to ones that other people created.

> Do you have a specific image you want behind the logo for parallaxing? I think there was another space-ier one from before?

Nothing in particular. Not sure where I got the space picture. Maybe peruse 500px.com and see if you can take a slice from something. We could even go with a negative space DVO and have something sweet as the background. Completely up to you though.
